services:
  backend:
    build: .
    ports:
      - 3000:3000
  database:
    image: postgres:15.3
    ports:
      - '5432:5432'
    # FYI: https://hub.docker.com/_/postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
